[package]
name = "MultiChainor"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5.4", features = ["full"] }
dotenv = "0.15.0"
lazy_static = "1.5.0"
tokio = { version = "1.41.0", features = ["full"] }
ureq = { version = "2.10.1", features = ["json"] }
