[package]
name = "MultiChainor"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5.4", features = ["full"] }
dotenv = "0.15.0"
tokio = { version = "1.41.0", features = ["full"] }
